"""enabled form

Revision ID: 54e4ed9c0c8c
Revises: a81b7d92813f
Create Date: 2026-04-11 23:52:23.811908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54e4ed9c0c8c'
down_revision: Union[str, Sequence[str], None] = 'a81b7d92813f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('enabled', sa.Boolean(), nullable=True, default=True))
    op.execute("UPDATE forms SET enabled = true")
    op.alter_column('forms', 'enabled', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'enabled')
    # ### end Alembic commands ###
