"""search setting model

Revision ID: 688202cbc052
Revises: 54e4ed9c0c8c
Create Date: 2026-04-12 14:11:54.307794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '688202cbc052'
down_revision: Union[str, Sequence[str], None] = '54e4ed9c0c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('gender_search', sa.String(length=20), nullable=False),
    sa.Column('geo_search', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_id')
    )

    op.create_index('idx_search_settings_form_id', 'search_settings', ['form_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_settings')
    # ### end Alembic commands ###
