"""lat and lon

Revision ID: a81b7d92813f
Revises: aa5fcad56877
Create Date: 2026-04-10 23:13:34.653292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a81b7d92813f'
down_revision: Union[str, Sequence[str], None] = 'aa5fcad56877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('latitude', sa.DECIMAL(precision=9, scale=6), nullable=True))
    op.add_column('forms', sa.Column('longitude', sa.DECIMAL(precision=9, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'longitude')
    op.drop_column('forms', 'latitude')
    # ### end Alembic commands ###
